service: aws-python-http-api-project-loom
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    lambda:
      mountCode: True
